name: iso-filecoin-react
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - master
    paths:
      - 'packages/iso-filecoin-react/**'
      - .github/workflows/iso-filecoin-react.yml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - 'packages/iso-filecoin-react/**'
      - .github/workflows/iso-filecoin-react.yml
      - pnpm-lock.yaml
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm -r --filter iso-filecoin-react run lint
      - run: pnpm -r --filter iso-filecoin-react exec depcheck
      - run: pnpm -r --filter iso-filecoin-react run test
        id: tests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
